version: "3.7"

services:
    db_primary:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: docker_dev
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: group24
        ports:
            - "3306:3306"
    db_auth:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: auth
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: group24
            MYSQL_TCP_PORT: 3307

        ports:
            - "3307:3307"
    
    
    primary:
        build: .
        image: webcalendar
        ports:
            - "3000:3000"
        volumes:
            - .:/app
        depends_on:
            - db_primary
        links:
            - db_primary
    auth:
        image: driftydirt/group24auth:0.0.7
        ports: 
            - "3001:3000"
        depends_on:
            - db_auth
        links:
            - db_auth
    mailer:
        image: driftydirt/group24mailer:0.0.3
        ports: 
            - "3002:3000"
