version: "3.7"

services:
    db_primary:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: docker_dev
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: group24
        ports:
            - "3306:3306"
    db_auth:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: auth
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: group24
            MYSQL_TCP_PORT: 3307

        ports:
            - "3307:3307"
    db_events:
        image: postgres:latest
        # volumes: 
        #     - db_data:/var/lib/mysql
        restart: always
        environment:
            POSTGRES_DB: event_microservice
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: group24

        ports:
            - 3308:3308
    

    redis:
        image: redis:latest
        restart: always
        ports:
        - '6379:6379'
        command: redis-server --save 20 1 --loglevel warning
        volumes: 
        - redis:/data
    sidekiq:
        depends_on:
        - 'redis'
        command: sidekiq -C config/sidekiq.yml
        image: driftydirt/group24mailer:0.0.9

    
    primary:
        build: .
        image: webcalendar
        ports:
            - "3000:3000"
        volumes:
            - .:/app
        depends_on:
            - db_primary
        links:
            - db_primary
    auth:
        image: driftydirt/group24auth:0.0.8
        ports: 
            - "3001:3000"
        depends_on:
            - db_auth
        links:
            - db_auth
    mailer:
        image: driftydirt/group24mailer:0.0.9
        ports: 
            - "3002:3000"
        environment: 
            REDIS_HOST: redis
            REDIS_PORT: 6379
        links:
            - redis
    event:
        image: driftydirt/group24events:0.0.1
        ports:
            - 3003:3000
        depends_on:
            - db_events
        links:
            - db_events
volumes:
    redis: 
        driver: local