development:
  primary:
    adapter: mysql2
    encoding: utf8
    host: db_primary
    username: root
    password: group24
    database: docker_dev

test:
  primary:
    adapter: mysql2
    encoding: utf8
    host: db_primary
    username: root
    password: group24
    database: docker_dev
