development:
  primary:
    adapter: mysql2
    encoding: utf8
    host: db_primary
    username: root
    password: group24
    database: docker_dev
  auth:
    adapter: mysql2
    encoding: utf8
    host: db_auth
    username: root
    password: group24
    database: auth
    port: 3307

test:
  primary:
    adapter: mysql2
    encoding: utf8
    host: db_primary
    username: root
    password: group24
    database: docker_dev
  auth:
    adapter: mysql2
    encoding: utf8
    host: db_auth
    username: root
    password: group24
    database: auth
    port: 3307
